[mypy]
python_version = 3.12
strict = true
plugins = pydantic.mypy
enable_error_code = redundant-cast,no-redef
disable_error_code = no-untyped-def,no-untyped-call,arg-type,type-arg,no-any-return,assignment,union-attr,attr-defined,return-value,annotation-unchecked,import-untyped
