"""Compatibility alias for model_compass."""

from __future__ import annotations

import model_compass
from model_compass import (
    BenchmarkError,
    BenchmarkQualityProvider,
    ConfigurationError,
    CostReconciliation,
    DependencyError,
    ExecutionError,
    ExecutionRequest,
    ExecutionResult,
    InMemoryQualityProvider,
    LiteLLMBackend,
    MetricEvidence,
    ModelCompassError,
    NoEligibleModelError,
    ObjectiveDirection,
    Observation,
    ParetoObjective,
    ParetoResult,
    PricingError,
    QualityProvider,
    RequestProfile,
    SelectedExecution,
    SelectionDataPolicy,
    SelectionError,
    SelectionPolicy,
    StorageError,
    UsageRecord,
    __version__,
    analytics,
    estimate_request_cost,
    pareto_analysis,
    pareto_frontier,
    select_model,
    wilson_lower_bound,
)

__all__ = [
    "BenchmarkError",
    "BenchmarkQualityProvider",
    "ConfigurationError",
    "CostReconciliation",
    "DependencyError",
    "ExecutionError",
    "ExecutionRequest",
    "ExecutionResult",
    "InMemoryQualityProvider",
    "LiteLLMBackend",
    "MetricEvidence",
    "ModelCompassError",
    "NoEligibleModelError",
    "ObjectiveDirection",
    "Observation",
    "ParetoObjective",
    "ParetoResult",
    "PricingError",
    "QualityProvider",
    "RequestProfile",
    "SelectedExecution",
    "SelectionDataPolicy",
    "SelectionError",
    "SelectionPolicy",
    "StorageError",
    "UsageRecord",
    "__version__",
    "analytics",
    "estimate_request_cost",
    "model_compass",
    "pareto_analysis",
    "pareto_frontier",
    "select_model",
    "wilson_lower_bound",
]
