"""Capability filtering, workload scenarios, comparisons, and model selection."""

from model_compass.selection.capabilities import (
    EligibilityResult,
    MissingDataPolicy,
    check_eligibility,
)
from model_compass.selection.comparison import (
    CandidateAnalysis,
    ComparisonReport,
    compare_models,
)
from model_compass.selection.constraints import (
    ConstraintResult,
    GatewayProviderAllowBlock,
    MaximumExpectedCost,
    MaximumLatency,
    MinimumContext,
    MinimumQuality,
    MinimumReliability,
    ModelIdAllowBlock,
    RequiredCapabilities,
    SelectionConstraint,
)
from model_compass.selection.engine import (
    CandidateAssessment,
    ObjectiveDirection,
    ParetoObjective,
    ParetoResult,
    RequestCostEstimate,
    SelectionDataPolicy,
    SelectionPolicy,
    SelectionResult,
    estimate_request_cost,
    pareto_analysis,
    pareto_frontier,
    select_model,
    wilson_lower_bound,
)
from model_compass.selection.evidence import (
    BenchmarkQualityProvider,
    InMemoryQualityProvider,
    MetricEvidence,
    QualityProvider,
    QualityResolutionRule,
    TieredQualityProvider,
    partition_quality_evidence,
    resolve_quality_evidence,
)
from model_compass.selection.scenarios import (
    WorkloadScenario,
    custom_workload_scenario,
    workload_scenario,
)

__all__ = [
    "BenchmarkQualityProvider",
    "CandidateAnalysis",
    "CandidateAssessment",
    "ComparisonReport",
    "ConstraintResult",
    "EligibilityResult",
    "GatewayProviderAllowBlock",
    "InMemoryQualityProvider",
    "MaximumExpectedCost",
    "MaximumLatency",
    "MetricEvidence",
    "MinimumContext",
    "MinimumQuality",
    "MinimumReliability",
    "MissingDataPolicy",
    "ModelIdAllowBlock",
    "ObjectiveDirection",
    "ParetoObjective",
    "ParetoResult",
    "QualityProvider",
    "QualityResolutionRule",
    "RequestCostEstimate",
    "RequiredCapabilities",
    "SelectionConstraint",
    "SelectionDataPolicy",
    "SelectionPolicy",
    "SelectionResult",
    "TieredQualityProvider",
    "WorkloadScenario",
    "check_eligibility",
    "compare_models",
    "custom_workload_scenario",
    "estimate_request_cost",
    "pareto_analysis",
    "pareto_frontier",
    "partition_quality_evidence",
    "resolve_quality_evidence",
    "select_model",
    "wilson_lower_bound",
    "workload_scenario",
]
